# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: tomislater
open_collective: # Replace with a single Open Collective username
ko_fi: tomislater
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: tomislater
issuehunt: tomislater
otechie: # Replace with a single Otechie username
